CREATE TABLE PERSON (
    CPF VARCHAR(12) NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	BIRTH_YEAR INTEGER,
	ADDRESS VARCHAR(255) NOT NULL,
	LAST_ADDRESS_UPDATE DATE NOT NULL,
	LAST_INCOME_UPDATE DATE,
	LAST_ASSETS_UPDATE DATE,
	LAST_DEBTS_UPDATE DATE
);

CREATE TABLE ASSETS (
    id UUID NOT NULL PRIMARY KEY,
	ORIGINAL_ID VARCHAR(255) NOT NULL,
	TYPE VARCHAR(255) NOT NULL,
	LOCALE VARCHAR(255) NOT NULL,
	ASSET_VALUE DECIMAL(12,4) NOT NULL,
	CPF VARCHAR(12),
	LAST_UPDATE DATE,
	CONSTRAINT ASSETS_CPF_FKEY FOREIGN KEY (CPF) REFERENCES PERSON (CPF)
);

CREATE TABLE INCOME (
    id UUID NOT NULL PRIMARY KEY,
	ORIGINAL_ID VARCHAR(255) NOT NULL,
	TYPE VARCHAR(255) NOT NULL,
	LOCALE VARCHAR(255) NOT NULL,
	INCOME_VALUE DECIMAL(12,4) NOT NULL,
	CPF VARCHAR(12),
	LAST_UPDATE DATE,
	FREQUENCY VARCHAR(255) NOT NULL,
	CONSTRAINT ASSETS_CPF_FKEY FOREIGN KEY (CPF) REFERENCES PERSON (CPF)
);

CREATE TABLE DEBT (
    id UUID NOT NULL PRIMARY KEY,
	ORIGINAL_ID VARCHAR(255) NOT NULL,
	ORIGINAL_DATE DATE NOT NULL,
	LAST_UPDATE DATE,
	STATUS VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	LOCALE VARCHAR(255) NOT NULL,
	DEBT_VALUE DECIMAL(12,4) NOT NULL,
	CPF VARCHAR(12),
	CONSTRAINT ASSETS_CPF_FKEY FOREIGN KEY (CPF) REFERENCES PERSON (CPF)
);


CREATE TABLE SEARCH_HISTORY (
    id UUID NOT NULL PRIMARY KEY,
	SEARCH_DATE DATE,
	USERNAME VARCHAR(255) NOT NULL,
	TOKEN VARCHAR(255) NOT NULL,
	CPF VARCHAR(12),
    CONSTRAINT ASSETS_CPF_FKEY FOREIGN KEY (CPF) REFERENCES PERSON (CPF)
);


CREATE TABLE DATA_CONTROL (
    id UUID NOT NULL PRIMARY KEY,
	LAST_UPDATE DATE,
	FIRST_LOADED BOOLEAN DEFAULT FALSE
);

INSERT INTO DATA_CONTROL (ID, LAST_UPDATE, FIRST_LOADED) VALUES ('a52a2f04-aee1-11e8-98d0-529269fb1459', null, false);
