before_script: cd dionysus
before_install: cd dionysus
language: java
jdk:
  - oraclejdk8
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V